package q3_kotlin.popular_libraries.myapplication.presenter

import q3_kotlin.popular_libraries.myapplication.view.PopularFilmsItemView

interface PopularMoviesListPresenter : IListPresenter<PopularFilmsItemView>